theme: jekyll-theme-cayman
title: RewinedDocs
description: [De plek voor onze documentatie!]
include: _includes/footer.html
include: _includes/breadcrumbs.html
include: _includes/breadcrumbs.html


breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
RepoName: RewinedDocs

github:
  is_project_page: false
